## Main task file for stv3-api role
# All the users, groups, directories and code are 
# set up by the common role.

---
- name: quincy.conf
  copy: src=quincy.conf dest=/etc/stv3/quincy.conf 
            owner=stv3 group=stv3 mode=0644
  notify: 
    - restart stv3-api

- name: stv3-api-initd
  copy: src=stv3-api.debian.init.d dest=/etc/init.d/stv3-api
        owner=stv3 group=stv3 mode=0755

- name: stv3-api
  debug: msg="Starting stv3-api"
  notify: 
    - restart stv3-api
